all: chercherfichier factorielle liste repertoire

chercherfichier: chercherfichier.c 
	gcc -o chercherfichier chercherfichier.c

factorielle: factorielle.c
	gcc -o factorielle factorielle.c

liste: liste.c liste.h
	gcc -o liste liste.c liste.h

repertoire: repertoire.c repertoire.h
	gcc -o repertoire repertoire.c repertoire.h

