all: operator octets fichier calcule etudiant_db couleur_compteur

operator: operator.c operator.h
	gcc -o operator operator.c operator.h

octets: octets.c
	gcc -o octets octets.c

fichier: fichier.c fichier.h
	gcc -o fichier fichier.c fichier.h

calcule: calcule.c calcule.h
	gcc -o calcule calcule.c calcule.h

etudiant_db: etudiant_db.c
	gcc -o etudiant_db etudiant_db.c

couleur_compteur: couleur_compteur.c
	gcc -o couleur_compteur couleur_compteur.c
